ids-base/ids/urls.py
from django.contrib import admin
from django.urls import path
from app.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", signin, name="signin"),
    path("data/", data, name="data"),
    path("addnew/", addnew, name="addnew"),
    path("edit/<int:id>", edit, name="edit"),
    path("update/<int:id>", update, name="update"),
    path("delete/<int:id>", destroy, name="destroy"), 
    path('process_csv/', process_csv, name='process_csv'),
    path('index/', index, name="index"),
    path('signup/', signup, name="signup"),
    path('signout/', signout, name="signout"),
    path("perform-detection/", perform_detection, name="perform_detection"),
]

ids-base/app/models.py
from django.db import models

# Create your models here.
class Data(models.Model):
    dur = models.FloatField(default=0.0)
    proto = models.CharField(max_length=10, default="")
    service = models.CharField(max_length=10, default="")
    state = models.CharField(max_length=10, default="")
    spkts = models.IntegerField(default=0)
    dpkts = models.IntegerField(default=0)
    sbytes = models.IntegerField(default=0)
    dbytes = models.IntegerField(default=0)
    rate = models.FloatField(default=0.0)
    sttl = models.IntegerField(default=0)
    dttl = models.IntegerField(default=0)
    sload = models.FloatField(default=0.0)
    dload = models.FloatField(default=0.0)
    sloss = models.IntegerField(default=0)
    dloss = models.IntegerField(default=0)
    sinpkt = models.FloatField(default=0.0)
    dinpkt = models.FloatField(default=0.0)
    sjit = models.FloatField(default=0.0)
    djit = models.FloatField(default=0.0)
    swin = models.IntegerField(default=0)
    stcpb = models.IntegerField(default=0)
    dtcpb = models.IntegerField(default=0)
    dwin = models.IntegerField(default=0)
    tcprtt = models.FloatField(default=0.0)
    synack = models.FloatField(default=0.0)
    ackdat = models.FloatField(default=0.0)
    smean = models.FloatField(default=0.0)
    dmean = models.FloatField(default=0.0)
    trans_depth = models.IntegerField(default=0)
    response_body_len = models.IntegerField(default=0)
    ct_srv_src = models.IntegerField(default=0)
    ct_state_ttl = models.IntegerField(default=0)
    ct_dst_ltm = models.IntegerField(default=0)
    ct_src_dport_ltm = models.IntegerField(default=0)
    ct_dst_sport_ltm = models.IntegerField(default=0)
    ct_dst_src_ltm = models.IntegerField(default=0)
    is_ftp_login = models.IntegerField(default=0)
    ct_ftp_cmd = models.IntegerField(default=0)
    ct_flw_http_mthd = models.IntegerField(default=0)
    ct_src_ltm = models.IntegerField(default=0)
    ct_srv_dst = models.IntegerField(default=0)
    is_sm_ips_ports = models.IntegerField(default=0)
    attack_cat = models.CharField(max_length=50, default='Normal')
    label = models.IntegerField(default=0)

    class Meta:
        db_table = "tbldata"

ids-base/app/templates/app/editdata.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Blank Page</title>
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
</head>


<body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

        <a class="navbar-brand mr-1" href="{% url 'index' %}">RF-IDS</a>

        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>
    </nav>

    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'data' %}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Log</span>
                </a>
            </li>
        </ul>

        <div id="content-wrapper">
            <div class="container-fluid">
                <!-- Page Content -->
                <div class="card mb-3">
                    <div class="card-header">
                        <i class="fas fa-table"></i>
                        Update Data
                    </div>
                    <div class="card-body">
                        <form method="POST" class="post-form" action="/update/{{ data.id }}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>ID:</label>
                                <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ data.id }}"/>
                            </div>
                            <div class="form-group">
                                <label>IP Source:</label>
                                <input type="text" class="form-control" name="source_ip" id="id_source_ip" required maxlength="30" value="{{ data.source_ip }}"/>
                            </div>
                            <div class="form-group">
                                <label>IP Destination:</label>
                                <input type="text" class="form-control" name="destination_ip" id="id_destination_ip" required maxlength="30" value="{{ data.destination_ip }}"/>
                            </div>
                            <div class="form-group">
                                <label>Port Source:</label>
                                <input type="text" class="form-control" name="source_port" id="id_source_port" required maxlength="30" value="{{ data.source_port }}"/>
                            </div>
                            <div class="form-group">
                                <label>Port Destination:</label>
                                <input type="text" class="form-control" name="destination_port" id="id_destination_port" required maxlength="30" value="{{ data.destination_port }}"/>
                            </div>
                            <div class="form-group">
                                <label>Protocol:</label>
                                <input type="text" class="form-control" name="protocol" id="id_.protocol" required maxlength="30" value="{{ data.protocol }}"/>
                            </div>
                            <div class="form-group">
                                <label>Packet Length:</label>
                                <input type="text" class="form-control" name="packet_length" id="id_packet_length" required maxlength="30" value="{{ data.packet_length }}"/>
                            </div>
                            <div class="form-group">
                                <label>Timestamp:</label>
                                <input type="text" class="form-control" name="timestamp" id="id_timestamp" value="{{ data.timestamp }}"/>
                            </div>
                            <div class="form-group">
                                <label>Flag Packet:</label>
                                <input type="text" class="form-control" name="flag_packet" id="id_flag_packet" required maxlength="30" value="{{ data.flag_packet }}"/>
                            </div>
                            <div class="form-group">
                                <label>Data Payload:</label>
                                <textarea class="form-control" name="data_payload" id="id_data_payload">{{ data.data_payload }}</textarea>
                            </div>
                            <div class="form-group">
                                <label>Label:</label>
                                <input type="text" class="form-control" name="label" id="id_label" required maxlength="10" value="{{ data.label }}"/>
                            </div>
                            
                            <button type="submit" class="btn btn-primary btn-sm"><i class="fas fa-save"></i> Update</button>
                        </form>
                        
                    </div>
                </div>
            </div>

            <!-- Sticky Footer -->
            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © Dzikri & Saepurizal</span>
                    </div>
                </div>
            </footer>

        </div>
        <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Page level plugin JavaScript-->
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'js/js.cookie.min.js' %}"></script>


    <!-- Demo scripts for this page-->
    <!-- <script src="{% static 'js/demo/datatables-demo.js' %} "></script> -->

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <script>
    
    </script>
</body>

ids-base/app/templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Blank Page</title>
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
</head>


<body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

        <a class="navbar-brand mr-1" href="{% url 'index' %}">RF-IDS</a>

        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>
    </nav>

    <div id="wrapper">
            <!-- Sidebar -->
            <ul class="sidebar navbar-nav">
                <!-- {% if user.is_authenticated %} -->
                <li class="nav-item">
                    <a href="#" class="nav-link">

                        <i class="fas fa-user-alt"></i>
                        <span> {{ user.username }}</span>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Deteksi Anomali</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'data' %}">
                        <i class="fas fa-fw fa-table"></i>
                        <span>Dataset</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'signout' %}" class="nav-link">
                    <i class="nav-icon fas fa-sign-out-alt"></i>
                    LogOut
                    </a>
                </li>
                <!-- {% endif %} -->
            </ul>

        <div id="content-wrapper">
            <div class="container-fluid">

                <!-- Icon Cards-->
                <div class="row">
                    <div class="col-xl-3 col-sm-6 mb-3">
                        <div class="card text-white bg-primary o-hidden h-100">
                            <div class="card-body">
                                <div class="card-body-icon">
                                    <i class="fas fa-fw fa-comments"></i>
                                </div>
                                Service Status
                                <hr>
                                <div class="mr-5" id="status"></div>
                            </div>
                            <a class="card-footer text-white clearfix small z-1">
                                {% csrf_token %}
                                <button type="submit" name="command_start" id="command_start" value="start" class="btn btn-success">Start</button>
                                <button type="submit" name="command_stop" id="command_stop" value="stop" class="btn btn-danger">Stop</button>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-sm-6 mb-3">
                        <div class="card text-white bg-warning o-hidden h-100" id="last_attack_card">
                            <div class="card-body">
                                <div class="card-body-icon">
                                    <i class="fas fa-fw fa-list"></i>
                                </div>
                                Last Attack
                                <hr>
                                <div class="mr-5" id="last_attack"></div>
                            </div>
                            <a class="card-footer text-white clearfix small z-1" href="#">
                                <span class="float-left">
                                    <i class="fas fa-clock"></i>
                                </span>
                                <span class="float-left" id="last_attack_footer"></span>
                            </a>
                        </div>
                    </div>
                </div>

                <!-- Page Content -->
                <div class="card mb-3">
                    <div class="card-header">
                        <i class="fas fa-table"></i>
                        Log Data
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data" id="detection-form">
                            {% csrf_token %}
                            <label for="csv_file">Upload CSV File:</label>
                            <input type="file" name="csv_file" id="csv_file" accept=".csv">
                            <button type="button" id="perform-detection" class="btn btn-primary btn-sm">Deteksi</button>
                        </form>
                        <hr>
                        <div id="detectionResult" style="display: none;">
                            <p>Hasil Deteksi:</p>
                            <div id="resultMessage"></div>
                        </div>
                    </div>
                </div>


            </div>
            <!-- /.container-fluid -->

            <!-- Sticky Footer -->
            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © Dzikri & Saepurizal</span>
                    </div>
                </div>
            </footer>

        </div>
        <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Page level plugin JavaScript-->
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'js/js.cookie.min.js' %}"></script>


    <!-- Demo scripts for this page-->
    <!-- <script src="{% static 'js/demo/datatables-demo.js' %} "></script> -->

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            var csrftoken = Cookies.get('csrftoken');
            
            // Event listener untuk tombol deteksi
            $("#perform-detection").on("click", function () {
                var formData = new FormData($("#detection-form")[0]);
                $.ajax({
                    type: "POST",
                    url: "{% url 'perform_detection' %}",  // Sesuaikan dengan URL yang benar
                    data: formData,
                    processData: false,
                    contentType: false,
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success: function (response) {
                        // Tampilkan hasil deteksi di dalam #detectionResult
                        $("#detectionResult").show();
                        $("#resultMessage").html(JSON.stringify(response));
                    },
                    error: function () {
                        console.error("Terjadi kesalahan saat melakukan deteksi");
                    }
                });
            });
        });
    </script>
</body>

ids-base/app/templates/app/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
    <style>
        body {
            font-family: "Open Sans", sans-serif;
            background: linear-gradient(120deg,#2980b9, #8e44ad);
        }
        .login-page {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
    }
    </style>
</head>
<body class="login-page">
    <div class="card" style="width:300px">
        <div class="card-header text-center"><h2>Login</h2></div>
        <div class="card-body">
            <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.username.label_tag }}
                <input type="text" class="form-control" id="{{ form.username.id_for_label }}"
                       name="{{ form.username.name }}">
            </div>
            <div class="form-group">
                {{ form.password.label_tag }}
                <input type="password" class="form-control" id="{{ form.password.id_for_label }}"
                       name="{{ form.password.name }}">
            </div>
            <br>
            <input type="submit" class="btn btn-primary floatright" value="Login" style="width:270px">
        </div>
        <div class="card-footer text-center">
            Tidak Punya Akun?
        <br><a href="{% url 'signup' %}">Register</a>
        </div>
    </div>
</body>
</html>

ids-base/app/templates/app/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Register User</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
    <style>
        body {
            font-family: "Open Sans", sans-serif;
            background: linear-gradient(120deg,#2980b9, #8e44ad);
        }
        .login-page {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }
    </style>
</head>
<body class="login-page">
    <div class="card" style="width:300px">
        <div class="card-header text-center">Register</div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                <p>
                    {{ field.label_tag }} <br>
                    {{ field }}
                    {% for error in field.errors %}
                    <p style="color: red;">{{ error }}</p>
                    {% endfor %}
                </p>
                {% endfor %}
                <br>
                <input type="submit" class="btn btn-primary floatright" value="Register" style="width:270px">
            </form>
        </div>
        <div class="card-footer text-center">
            Sudah Punya Akun?
        <br><a href="{% url 'signin' %}">Sign In</a>
        </div>
    </div>
</body>
</html> 